### ISSUE TITLE
Make this repo private?

### ISSUE THREAD

**Issue by bocharsky-bw** [SymfonyCasts/solid-diego#2]
@larzuk91 should we make this repo private? Do you use it publicly somehow, e.g. linking to it from the local project?

I see we already have the official repo: https://github.com/SymfonyCasts/solid

**Comment by MolloKhan** [comment]
Nope, I'm not using it in other places, it could be private but eventually, it will replace the other SOLID repo so I think if it stays public or not is not a thing to worry about

**Comment by bocharsky-bw** [comment]
OK, thanks for clarifying!
